package comp5216.sydney.edu.fridgebutler.Map;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.HashMap;
import java.util.Map;

import comp5216.sydney.edu.fridgebutler.EditItem.MainActivity;
import comp5216.sydney.edu.fridgebutler.R;

/**
 * Help user connect with others
 * User can put on a request and it would
 * show on map so other user can see it
 */
public class UpItem extends AppCompatActivity {
    String TAG = this.getClass().getSimpleName();
    EditText address, phone, message;
    Button save;
    Button delete;

    String user_id;
    FirebaseFirestore db;
    FirebaseAuth firebaseAuth;
    String shoppingList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_up_item);

        address = findViewById(R.id.unit);
        phone = findViewById(R.id.Phone);
        save = findViewById(R.id.Upload);
        message = findViewById(R.id.Message);
        delete = findViewById(R.id.deleteRequest);

        Bundle extras = getIntent().getExtras();
        if (extras != null) {
            shoppingList = extras.getString("shoppingList");
        }

        //initialise database instance
        db = FirebaseFirestore.getInstance();
        firebaseAuth = FirebaseAuth.getInstance();
        user_id = firebaseAuth.getCurrentUser().getUid();

        //set action when user click on save button
        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                addItemOnclick();
            }
        });

        //set action when user click delete button
        delete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                AlertDialog.Builder builder = new AlertDialog.Builder(UpItem.this);
                builder.setTitle("Do you want to delete your current request?")
                        .setPositiveButton("Cancel", new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialogInterface, int i) {

                            }
                        })
                        .setNegativeButton("Yes", new DialogInterface.OnClickListener() {
                            @RequiresApi(api = Build.VERSION_CODES.O)
                            public void onClick(DialogInterface dialogInterface, int i) {
                                DocumentReference docRef = db.collection("service").document(user_id);
                                docRef.delete();
                                startActivity(new Intent(UpItem.this, MainActivity.class));
                            }
                        });

                builder.create().show();
            }
        });
    }

    //set method to execution once customer click save button
    public void addItemOnclick() {
        String addressString = address.getText().toString().trim();
        String phoneNumber = phone.getText().toString().trim();
        String messageType = message.getText().toString().trim();
        Map < String, Object > info = new HashMap < > ();
        info.put("Address", addressString);
        info.put("Phone", phoneNumber);

        if (shoppingList != null) {
            info.put("Message", shoppingList);
            info.put("Type", "autoGenerated");
        } else {
            info.put("Message", messageType);
            info.put("Type", "General");
        }

        DocumentReference docRef = db.collection("service").document(user_id);
        docRef.set(info);
        startActivity(new Intent(UpItem.this, MainActivity.class));
    }
}